//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rekrutacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class klient
    {
        public klient()
        {
            this.email = new HashSet<email>();
            this.telefon = new HashSet<telefon>();
        }
    
        public int id { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public int limit_kredytowy { get; set; }
        public string status { get; set; }
        public int branza_id { get; set; }
    
        public virtual branza branza { get; set; }
        public virtual ICollection<email> email { get; set; }
        public virtual ICollection<telefon> telefon { get; set; }
    }
}
