//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rekrutacja
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RekrutacjaEntitie : DbContext
    {
        public RekrutacjaEntitie()
            : base("name=RekrutacjaEntitie")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<branza> branza { get; set; }
        public DbSet<email> email { get; set; }
        public DbSet<klient> klient { get; set; }
        public DbSet<telefon> telefon { get; set; }
        public DbSet<select_branza> select_branza { get; set; }
        public DbSet<select_klient> select_klient { get; set; }
        public DbSet<select_mail> select_mail { get; set; }
        public DbSet<select_number> select_number { get; set; }
    }
}
