//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rekrutacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class select_branza
    {
        public string Nazwa { get; set; }
        public Nullable<int> Liczba_klientow { get; set; }
        public Nullable<int> Suma_limitu { get; set; }
    }
}
