//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rekrutacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class select_klient
    {
        public int ID { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public int Limit_kredytowy { get; set; }
        public string Status { get; set; }
        public string Branza { get; set; }
        public string E_mail { get; set; }
        public int numer_telefonu { get; set; }
    }
}
